// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClgEq41HoT_pY701Oi-jglIXQX7IczVDI',
    appId: '1:771231815277:web:0414652e565be56d655164',
    messagingSenderId: '771231815277',
    projectId: 'fleexa-d36d3',
    authDomain: 'fleexa-d36d3.firebaseapp.com',
    storageBucket: 'fleexa-d36d3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMb8gapK1WnRbrpxgxvx9RxkwiEJgUJY0',
    appId: '1:771231815277:android:6fb867eaecb7d2b2655164',
    messagingSenderId: '771231815277',
    projectId: 'fleexa-d36d3',
    storageBucket: 'fleexa-d36d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5zb9wrdxAlN2VSn1z6faDBbul5qc5Ous',
    appId: '1:771231815277:ios:daf9ee9b70ab9023655164',
    messagingSenderId: '771231815277',
    projectId: 'fleexa-d36d3',
    storageBucket: 'fleexa-d36d3.firebasestorage.app',
    iosBundleId: 'com.example.fleexa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5zb9wrdxAlN2VSn1z6faDBbul5qc5Ous',
    appId: '1:771231815277:ios:daf9ee9b70ab9023655164',
    messagingSenderId: '771231815277',
    projectId: 'fleexa-d36d3',
    storageBucket: 'fleexa-d36d3.firebasestorage.app',
    iosBundleId: 'com.example.fleexa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClgEq41HoT_pY701Oi-jglIXQX7IczVDI',
    appId: '1:771231815277:web:ecf9331d3cba2014655164',
    messagingSenderId: '771231815277',
    projectId: 'fleexa-d36d3',
    authDomain: 'fleexa-d36d3.firebaseapp.com',
    storageBucket: 'fleexa-d36d3.firebasestorage.app',
  );
}
